"""OpenAPI and JSON Schema import helpers."""

from objectified_cli.import_.detect import (
    DocumentKind,
    describe_document_format,
    detect_document_kind,
    is_draft_2020_12_schema_uri,
    is_recognized_json_schema_draft_uri,
    looks_like_arazzo,
    looks_like_arazzo_filename,
    looks_like_json_schema,
    looks_like_openapi,
    recommended_import_command,
    resolve_auto_import_command,
    unrecognized_auto_import_message,
    wrong_importer_message,
)
from objectified_cli.import_.source import load_import_document
from objectified_cli.import_.json_schema import (
    JsonSchemaStructureError,
    JsonSchemaTarget,
    detect_target,
    infer_name,
    load_and_validate_json_schema_file,
    load_json_schema_file,
    source_basename,
    validate_json_schema_structure,
    validate_json_schema_type_structure,
)
from objectified_cli.import_.openapi import (
    OpenApiStructureError,
    OpenApiVersionInfo,
    detect_openapi_version,
    load_and_validate_openapi_file,
    load_openapi_file,
    validate_openapi_structure,
)
from objectified_cli.import_.publish import (
    PUBLISH_FLAG_HELP,
    TYPE_PUBLISH_FLAG_HELP,
    normalize_cli_import_visibility,
    resolve_publish_visibility,
    resolve_type_publish_system,
)

__all__ = [
    "DocumentKind",
    "JsonSchemaStructureError",
    "JsonSchemaTarget",
    "OpenApiStructureError",
    "OpenApiVersionInfo",
    "PUBLISH_FLAG_HELP",
    "TYPE_PUBLISH_FLAG_HELP",
    "normalize_cli_import_visibility",
    "resolve_publish_visibility",
    "resolve_type_publish_system",
    "describe_document_format",
    "detect_document_kind",
    "detect_openapi_version",
    "detect_target",
    "infer_name",
    "is_draft_2020_12_schema_uri",
    "is_recognized_json_schema_draft_uri",
    "load_and_validate_json_schema_file",
    "load_and_validate_openapi_file",
    "load_import_document",
    "load_json_schema_file",
    "load_openapi_file",
    "looks_like_arazzo",
    "looks_like_arazzo_filename",
    "looks_like_json_schema",
    "looks_like_openapi",
    "recommended_import_command",
    "resolve_auto_import_command",
    "source_basename",
    "unrecognized_auto_import_message",
    "validate_json_schema_structure",
    "validate_json_schema_type_structure",
    "validate_openapi_structure",
    "wrong_importer_message",
]
