.TH OBJECTIFIED\-HELP 1 "" "" "User Commands"
.SH NAME
objectified help \- Display help for <%= config.bin %>.
.SH DESCRIPTION
.nf
USAGE
  $ objectified help [COMMAND...] [-n]

ARGUMENTS
  [COMMAND...]  Command to show help for.

DESCRIPTION
  Display help for objectified.

OTHER
  -n, --nested-commands  Include all nested commands in the output.
.fi
