/**
 * Default offline responder used by the Studio AI chatbot until the Ollama
 * adapter lands (#259, #265).
 *
 * The replies are deterministic and intentionally cover every UI affordance
 * the interface guidelines call for so designers and reviewers can see the
 * chrome end-to-end without running a model:
 *   - Markdown rendering (headings, lists, inline code)
 *   - A fenced code block with copy + syntax highlighting
 *   - A ```json``` block holding a small but valid OpenAPI 3.1 spec so the
 *     "Import OpenAPI spec" affordance lights up
 */

import type { ChatSendFn } from './types';

const SPEC_DEMO_PROMPTS = ['openapi', 'spec', 'schema', 'api'];

export const createDemoChatResponder = (): ChatSendFn => async ({ prompt, isRegenerate }) => {
  const lower = prompt.toLowerCase();
  const wantsSpec = SPEC_DEMO_PROMPTS.some((needle) => lower.includes(needle));
  const variation = isRegenerate ? '\n\n_Regenerated with a slightly different angle._' : '';

  if (wantsSpec) {
    return [
      "Here's a small OpenAPI 3.1 sketch for what you described — review the JSON below and click **Import OpenAPI spec** to load it into Studio.",
      '',
      '```json',
      JSON.stringify(SAMPLE_SPEC, null, 2),
      '```',
      '',
      'A few things to consider next:',
      '- Tighten property descriptions for documentation scoring',
      '- Add `examples` arrays where missing',
      '- Decide whether to expose this through a path operation in a follow-up',
    ].join('\n') + variation;
  }

  return [
    "I'm the offline preview of the Studio AI assistant — the live model lands in a follow-up ticket. Until then, here's what the chat surface supports today:",
    '',
    '- **Markdown** rendering with headings, lists, and inline `code`',
    '- Code blocks with copy + syntax highlighting:',
    '',
    '```ts',
    "function greet(name: string): string {",
    "  return `Hello, ${name}!`;",
    "}",
    '```',
    '',
    'Try asking for an "OpenAPI spec" to see the import affordance.',
  ].join('\n') + variation;
};

const SAMPLE_SPEC = {
  openapi: '3.1.0',
  info: {
    title: 'Sample Catalog API',
    version: '0.1.0',
    description: 'Tiny catalog API generated by the Studio AI demo responder.',
  },
  components: {
    schemas: {
      Product: {
        type: 'object',
        description: 'A purchasable item in the catalog.',
        properties: {
          id: { type: 'string', format: 'uuid', description: 'Catalog identifier' },
          name: { type: 'string', description: 'Display name shown to shoppers' },
          priceCents: { type: 'integer', minimum: 0, description: 'Price in cents' },
        },
        required: ['id', 'name', 'priceCents'],
      },
    },
  },
};
