-- Add vectorization support to data_snapshot for LLM/semantic search.
-- Requires: pgvector extension (created in base schema 20251026-012616.sql).

SET search_path TO odb, public;

-- Ensure pgvector is available (no-op if already created)
CREATE EXTENSION IF NOT EXISTS vector;

-- Dimension 2000 fits pgvector HNSW index limit (max 2000) and works with qwen3-embedding:4b (request dimensions: 2000).
ALTER TABLE odb.data_snapshot
  ADD COLUMN IF NOT EXISTS embedding vector(2000) NULL,
  ADD COLUMN IF NOT EXISTS embedding_model text NULL,
  ADD COLUMN IF NOT EXISTS embedding_updated_at TIMESTAMP WITH TIME ZONE NULL;

COMMENT ON COLUMN odb.data_snapshot.embedding IS 'Vector embedding of data (or a text representation) for semantic/LLM search; generated by an embedding model';
COMMENT ON COLUMN odb.data_snapshot.embedding_model IS 'Name of the embedding model used (e.g. qwen3-embedding:4b) for re-vectorization and debugging';
COMMENT ON COLUMN odb.data_snapshot.embedding_updated_at IS 'When the embedding was last generated or updated';

-- HNSW index for fast approximate nearest-neighbor search using cosine distance (<=>).
-- Use in queries: ORDER BY embedding <=> query_vector LIMIT k
CREATE INDEX IF NOT EXISTS idx_data_snapshot_embedding_hnsw
  ON odb.data_snapshot
  USING hnsw (embedding vector_cosine_ops)
  WHERE embedding IS NOT NULL;
