-- Ensure data_snapshot.embedding is vector(2000); pgvector HNSW index max is 2000.
-- Aligns with REST embedding service EMBEDDING_DIMENSIONS = 2000.

SET search_path TO odb, public;

DROP INDEX IF EXISTS idx_data_snapshot_embedding_hnsw;

ALTER TABLE odb.data_snapshot
  DROP COLUMN IF EXISTS embedding,
  ADD COLUMN embedding vector(2000) NULL;

COMMENT ON COLUMN odb.data_snapshot.embedding IS 'Vector embedding of data (or a text representation) for semantic/LLM search; generated by an embedding model';

CREATE INDEX IF NOT EXISTS idx_data_snapshot_embedding_hnsw
  ON odb.data_snapshot
  USING hnsw (embedding vector_cosine_ops)
  WHERE embedding IS NOT NULL;
