import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import SessionWrapper from "@/app/components/auth/SessionWrapper";
import * as React from 'react';
import SideNav from '@/app/components/ade/dashboard/SideNav';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <div style={{ display: "flex", height: "calc(100vh - 48px)" }}>
        <SideNav/>

        <main style={{ flex: 1, overflow: "auto" }}>
          {children}
        </main>
      </div>
    </SessionWrapper>
  );
}
