"""
API tests for change-report template endpoints (CR-03, #2701).

Covers: list, create, set tenant default, set project default —
auth requirements, tenant scoping, semver 409, and clearing defaults.
"""

from datetime import datetime, timezone
from unittest.mock import patch

import pytest
from fastapi.testclient import TestClient

from app.auth import validate_authentication
from app.main import app

client = TestClient(app)

# ---------------------------------------------------------------------------
# Shared auth fixtures
# ---------------------------------------------------------------------------

_JWT_ADMIN = {
    "tenant_id": "t1",
    "user_id": "admin-user",
    "auth_method": "jwt",
}

_JWT_NON_ADMIN = {
    "tenant_id": "t1",
    "user_id": "plain-user",
    "auth_method": "jwt",
}

_API_KEY = {
    "tenant_id": "t1",
    "tenant_slug": "tn",
    "auth_method": "api_key",
}

# ---------------------------------------------------------------------------
# Shared data fixtures
# ---------------------------------------------------------------------------

_TEMPLATE_SUMMARY = {
    "id": "tmpl-1",
    "semver": "1.0.0",
    "owner_tenant_id": "t1",
    "created_at": datetime(2026, 4, 14, 12, 0, 0, tzinfo=timezone.utc),
}

_TEMPLATE_FULL_ROW = {
    **_TEMPLATE_SUMMARY,
    "header_template": "# {{productName}}",
    "body_template": "## Summary",
    "footnote_template": "Generator: {{generatorVersion}}",
    "created_by": "admin-user",
}

_PROJECT_ROW = {
    "id": "p1",
    "tenant_id": "t1",
    "creator_id": "admin-user",
    "name": "MyProject",
    "slug": "myproject",
    "enabled": True,
    "metadata": {},
    "change_report_template_version_id": None,
    "created_at": datetime(2026, 4, 14, 10, 0, 0, tzinfo=timezone.utc),
    "updated_at": datetime(2026, 4, 14, 10, 0, 0, tzinfo=timezone.utc),
}

_VALID_TEMPLATE_BODY = {
    "semver": "2.0.0",
    "headerTemplate": "# {{productName}}",
    "bodyTemplate": "## Body",
    "footnoteTemplate": "Generated by {{generatorVersion}}",
}


@pytest.fixture(autouse=True)
def _default_auth():
    """Default to JWT admin for all tests; individual tests may override."""
    app.dependency_overrides[validate_authentication] = lambda: _JWT_ADMIN
    yield
    app.dependency_overrides.pop(validate_authentication, None)


# ===========================================================================
# LIST change-report-template-versions
# ===========================================================================


def test_list_templates_ok():
    with patch("app.change_report_template_routes.db") as mdb:
        mdb.list_change_report_template_version_summaries.return_value = [_TEMPLATE_SUMMARY]
        r = client.get("/v1/tenants/tn/change-report-template-versions")
    assert r.status_code == 200
    items = r.json()
    assert len(items) == 1
    assert items[0]["id"] == "tmpl-1"
    assert items[0]["semver"] == "1.0.0"


def test_list_templates_empty():
    with patch("app.change_report_template_routes.db") as mdb:
        mdb.list_change_report_template_version_summaries.return_value = []
        r = client.get("/v1/tenants/tn/change-report-template-versions")
    assert r.status_code == 200
    assert r.json() == []


def test_list_templates_scoped_to_caller_tenant():
    """DB layer is called with the tenant_id from the JWT, not from the URL slug."""
    with patch("app.change_report_template_routes.db") as mdb:
        mdb.list_change_report_template_version_summaries.return_value = []
        client.get("/v1/tenants/some-other-slug/change-report-template-versions")
        mdb.list_change_report_template_version_summaries.assert_called_once_with("t1")


# ===========================================================================
# CREATE change-report-template-version
# ===========================================================================


def test_create_template_ok():
    with patch("app.change_report_template_routes.db") as mdb:
        mdb.is_user_tenant_admin.return_value = True
        mdb.insert_change_report_template_version.return_value = _TEMPLATE_FULL_ROW
        r = client.post(
            "/v1/tenants/tn/change-report-template-versions",
            json=_VALID_TEMPLATE_BODY,
        )
    assert r.status_code == 200
    body = r.json()
    assert body["semver"] == "1.0.0"
    assert "headerTemplate" in body


def test_create_template_requires_jwt():
    """API-key callers must be rejected with 403."""
    app.dependency_overrides[validate_authentication] = lambda: _API_KEY
    r = client.post(
        "/v1/tenants/tn/change-report-template-versions",
        json=_VALID_TEMPLATE_BODY,
    )
    assert r.status_code == 403


def test_create_template_non_admin_forbidden():
    """Non-admin JWT must be rejected with 403."""
    app.dependency_overrides[validate_authentication] = lambda: _JWT_NON_ADMIN
    with patch("app.change_report_template_routes.db") as mdb:
        mdb.is_user_tenant_admin.return_value = False
        r = client.post(
            "/v1/tenants/tn/change-report-template-versions",
            json=_VALID_TEMPLATE_BODY,
        )
    assert r.status_code == 403


def test_create_template_invalid_semver_400():
    with patch("app.change_report_template_routes.db") as mdb:
        mdb.is_user_tenant_admin.return_value = True
        r = client.post(
            "/v1/tenants/tn/change-report-template-versions",
            json={**_VALID_TEMPLATE_BODY, "semver": ""},
        )
    assert r.status_code == 400


def test_create_template_invalid_mustache_400():
    """A syntactically invalid Mustache template must return 400."""
    with patch("app.change_report_template_routes.db") as mdb:
        mdb.is_user_tenant_admin.return_value = True
        r = client.post(
            "/v1/tenants/tn/change-report-template-versions",
            json={**_VALID_TEMPLATE_BODY, "headerTemplate": "{{unclosed"},
        )
    assert r.status_code == 400


def test_create_template_duplicate_semver_409():
    """Unique-constraint violation from DB must surface as 409."""
    with patch("app.change_report_template_routes.db") as mdb:
        mdb.is_user_tenant_admin.return_value = True
        mdb.insert_change_report_template_version.side_effect = Exception(
            "duplicate key value violates unique constraint (23505)"
        )
        r = client.post(
            "/v1/tenants/tn/change-report-template-versions",
            json=_VALID_TEMPLATE_BODY,
        )
    assert r.status_code == 409
    assert "already exists" in r.json()["detail"].lower()


def test_create_template_scoped_to_caller_tenant():
    """insert call uses tenant_id from JWT, not URL."""
    with patch("app.change_report_template_routes.db") as mdb:
        mdb.is_user_tenant_admin.return_value = True
        mdb.insert_change_report_template_version.return_value = _TEMPLATE_FULL_ROW
        client.post(
            "/v1/tenants/some-other-slug/change-report-template-versions",
            json=_VALID_TEMPLATE_BODY,
        )
        call_kwargs = mdb.insert_change_report_template_version.call_args
        assert call_kwargs.kwargs["tenant_id"] == "t1"


# ===========================================================================
# PUT tenant default
# ===========================================================================


def test_set_tenant_default_ok():
    with patch("app.change_report_template_routes.db") as mdb, patch(
        "app.change_report_template_routes.template_accessible_to_tenant", return_value=True
    ):
        mdb.is_user_tenant_admin.return_value = True
        mdb.get_change_report_template_version_by_id.return_value = _TEMPLATE_FULL_ROW
        r = client.put(
            "/v1/tenants/tn/change-report-template-default",
            json={"templateVersionId": "tmpl-1"},
        )
    assert r.status_code == 200
    assert r.json()["status"] == "ok"


def test_set_tenant_default_clear_null():
    """Passing null clears the tenant default (no 404 lookup)."""
    with patch("app.change_report_template_routes.db") as mdb:
        mdb.is_user_tenant_admin.return_value = True
        r = client.put(
            "/v1/tenants/tn/change-report-template-default",
            json={"templateVersionId": None},
        )
    assert r.status_code == 200
    mdb.set_tenant_change_report_template_version.assert_called_once_with("t1", None)


def test_set_tenant_default_requires_jwt():
    app.dependency_overrides[validate_authentication] = lambda: _API_KEY
    r = client.put(
        "/v1/tenants/tn/change-report-template-default",
        json={"templateVersionId": None},
    )
    assert r.status_code == 403


def test_set_tenant_default_non_admin_forbidden():
    app.dependency_overrides[validate_authentication] = lambda: _JWT_NON_ADMIN
    with patch("app.change_report_template_routes.db") as mdb:
        mdb.is_user_tenant_admin.return_value = False
        r = client.put(
            "/v1/tenants/tn/change-report-template-default",
            json={"templateVersionId": None},
        )
    assert r.status_code == 403


def test_set_tenant_default_template_not_found_404():
    with patch("app.change_report_template_routes.db") as mdb:
        mdb.is_user_tenant_admin.return_value = True
        mdb.get_change_report_template_version_by_id.return_value = None
        r = client.put(
            "/v1/tenants/tn/change-report-template-default",
            json={"templateVersionId": "nonexistent"},
        )
    assert r.status_code == 404


def test_set_tenant_default_template_not_accessible_400():
    with patch("app.change_report_template_routes.db") as mdb, patch(
        "app.change_report_template_routes.template_accessible_to_tenant", return_value=False
    ):
        mdb.is_user_tenant_admin.return_value = True
        mdb.get_change_report_template_version_by_id.return_value = _TEMPLATE_FULL_ROW
        r = client.put(
            "/v1/tenants/tn/change-report-template-default",
            json={"templateVersionId": "tmpl-foreign"},
        )
    assert r.status_code == 400


# ===========================================================================
# PUT project default
# ===========================================================================


def test_set_project_default_ok_by_creator():
    with patch("app.change_report_template_routes.db") as mdb, patch(
        "app.change_report_template_routes.template_accessible_to_tenant", return_value=True
    ):
        mdb.get_project_by_id.return_value = {**_PROJECT_ROW, "creator_id": "admin-user"}
        mdb.is_user_tenant_admin.return_value = False
        mdb.get_change_report_template_version_by_id.return_value = _TEMPLATE_FULL_ROW
        mdb.update_project.return_value = _PROJECT_ROW
        r = client.put(
            "/v1/tenants/tn/projects/p1/change-report-template-default",
            json={"templateVersionId": "tmpl-1"},
        )
    assert r.status_code == 200


def test_set_project_default_ok_by_tenant_admin():
    with patch("app.change_report_template_routes.db") as mdb, patch(
        "app.change_report_template_routes.template_accessible_to_tenant", return_value=True
    ):
        # Creator is someone else, but the caller is a tenant admin
        mdb.get_project_by_id.return_value = {**_PROJECT_ROW, "creator_id": "other-user"}
        mdb.is_user_tenant_admin.return_value = True
        mdb.get_change_report_template_version_by_id.return_value = _TEMPLATE_FULL_ROW
        mdb.update_project.return_value = _PROJECT_ROW
        r = client.put(
            "/v1/tenants/tn/projects/p1/change-report-template-default",
            json={"templateVersionId": "tmpl-1"},
        )
    assert r.status_code == 200


def test_set_project_default_forbidden_non_creator_non_admin():
    with patch("app.change_report_template_routes.db") as mdb:
        app.dependency_overrides[validate_authentication] = lambda: _JWT_NON_ADMIN
        mdb.get_project_by_id.return_value = {**_PROJECT_ROW, "creator_id": "other-user"}
        mdb.is_user_tenant_admin.return_value = False
        r = client.put(
            "/v1/tenants/tn/projects/p1/change-report-template-default",
            json={"templateVersionId": None},
        )
    assert r.status_code == 403


def test_set_project_default_project_not_found_404():
    with patch("app.change_report_template_routes.db") as mdb:
        mdb.get_project_by_id.return_value = None
        r = client.put(
            "/v1/tenants/tn/projects/nonexistent/change-report-template-default",
            json={"templateVersionId": None},
        )
    assert r.status_code == 404


def test_set_project_default_clear_null():
    """Passing null clears the project override (no template lookup)."""
    with patch("app.change_report_template_routes.db") as mdb:
        mdb.get_project_by_id.return_value = {**_PROJECT_ROW, "creator_id": "admin-user"}
        mdb.is_user_tenant_admin.return_value = False
        mdb.update_project.return_value = _PROJECT_ROW
        r = client.put(
            "/v1/tenants/tn/projects/p1/change-report-template-default",
            json={"templateVersionId": None},
        )
    assert r.status_code == 200
    call_args = mdb.update_project.call_args
    assert call_args.args[2]["change_report_template_version_id"] is None


def test_set_project_default_requires_jwt():
    app.dependency_overrides[validate_authentication] = lambda: _API_KEY
    r = client.put(
        "/v1/tenants/tn/projects/p1/change-report-template-default",
        json={"templateVersionId": None},
    )
    assert r.status_code == 403
