'use client';

import React, { useState, useEffect } from 'react';
import Box from '@mui/material/Box';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import IconButton from '@mui/material/IconButton';
import { Close, Save } from '@mui/icons-material';
import { useDarkMode } from '../../../../hooks/useDarkMode';
import {
  getOperationDescription,
  upsertOperationDescription,
} from '../../../../../../lib/db/helper-path-operation-descriptions';
import { generateOperationId } from '../../../../../../lib/utils/path-utils';

interface OperationPropertiesPanelProps {
  operationId: string | null;
  operation: string;
  pathname: string;
  onClose: () => void;
}

export default function OperationPropertiesPanel({
  operationId,
  operation,
  pathname,
  onClose,
}: OperationPropertiesPanelProps) {
  const isDark = useDarkMode();
  const [summary, setSummary] = useState('');
  const [description, setDescription] = useState('');
  const [operationIdName, setOperationIdName] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [isSaving, setIsSaving] = useState(false);

  // Load operation description when operationId changes
  useEffect(() => {
    if (!operationId) {
      setSummary('');
      setDescription('');
      setOperationIdName('');
      return;
    }

    const loadDescription = async () => {
      setIsLoading(true);
      try {
        const result = await getOperationDescription(operationId);
        const desc = JSON.parse(result);

        if (desc) {
          setSummary(desc.summary || '');
          setDescription(desc.description || '');
          setOperationIdName(desc.operation_id || '');
        } else {
          // Auto-generate operation ID if none exists
          const autoGenerated = generateOperationId(pathname, operation);
          setOperationIdName(autoGenerated);
        }
      } catch (error) {
        console.error('Error loading operation description:', error);
      } finally {
        setIsLoading(false);
      }
    };

    loadDescription();
  }, [operationId, pathname, operation]);

  const handleSave = async () => {
    if (!operationId) return;

    setIsSaving(true);
    try {
      await upsertOperationDescription(
        operationId,
        summary,
        description,
        operationIdName
      );
      onClose();
    } catch (error) {
      console.error('Error saving operation description:', error);
      alert('Failed to save operation description. Please try again.');
    } finally {
      setIsSaving(false);
    }
  };

  if (!operationId) return null;

  return (
    <Box
      sx={{
        width: 320,
        height: '100%',
        borderLeft: isDark ? '1px solid #334155' : '1px solid #e2e8f0',
        background: isDark
          ? 'linear-gradient(180deg, #1e293b 0%, #0f172a 100%)'
          : 'linear-gradient(180deg, #ffffff 0%, #f8fafc 100%)',
        display: 'flex',
        flexDirection: 'column',
      }}
    >
      {/* Header */}
      <Box
        sx={{
          p: 2,
          borderBottom: isDark ? '1px solid #334155' : '1px solid #e2e8f0',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
        }}
      >
        <Box>
          <span className="text-sm font-semibold text-gray-900 dark:text-white">
            Operation Details
          </span>
          <div className="text-xs text-gray-500 dark:text-gray-400 mt-1">
            {operation} {pathname}
          </div>
        </Box>
        <IconButton size="small" onClick={onClose} sx={{ color: isDark ? '#94a3b8' : '#64748b' }}>
          <Close sx={{ fontSize: 18 }} />
        </IconButton>
      </Box>

      {/* Content */}
      {isLoading ? (
        <Box sx={{ p: 3, display: 'flex', justifyContent: 'center' }}>
          <span className="text-sm text-gray-500 dark:text-gray-400">Loading...</span>
        </Box>
      ) : (
        <>
          <Box sx={{ flex: 1, overflow: 'auto', p: 2 }}>
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
              {/* Operation ID */}
              <Box>
                <label className="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Operation ID
                </label>
                <TextField
                  fullWidth
                  size="small"
                  value={operationIdName}
                  onChange={(e) => setOperationIdName(e.target.value)}
                  placeholder="Auto-generated from path and verb"
                  sx={{
                    '& .MuiInputBase-root': {
                      fontSize: '0.875rem',
                      backgroundColor: isDark ? '#0f172a' : '#ffffff',
                      color: isDark ? '#f1f5f9' : '#0f172a',
                    },
                    '& .MuiOutlinedInput-notchedOutline': {
                      borderColor: isDark ? '#334155' : '#e2e8f0',
                    },
                  }}
                />
                <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                  Used for code generation and API client SDKs
                </p>
              </Box>

              {/* Summary */}
              <Box>
                <label className="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Summary
                </label>
                <TextField
                  fullWidth
                  size="small"
                  value={summary}
                  onChange={(e) => setSummary(e.target.value)}
                  placeholder="Brief summary of the operation"
                  sx={{
                    '& .MuiInputBase-root': {
                      fontSize: '0.875rem',
                      backgroundColor: isDark ? '#0f172a' : '#ffffff',
                      color: isDark ? '#f1f5f9' : '#0f172a',
                    },
                    '& .MuiOutlinedInput-notchedOutline': {
                      borderColor: isDark ? '#334155' : '#e2e8f0',
                    },
                  }}
                />
              </Box>

              {/* Description */}
              <Box>
                <label className="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Description
                </label>
                <TextField
                  fullWidth
                  multiline
                  rows={6}
                  size="small"
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  placeholder="Detailed description of what this operation does..."
                  sx={{
                    '& .MuiInputBase-root': {
                      fontSize: '0.875rem',
                      backgroundColor: isDark ? '#0f172a' : '#ffffff',
                      color: isDark ? '#f1f5f9' : '#0f172a',
                    },
                    '& .MuiOutlinedInput-notchedOutline': {
                      borderColor: isDark ? '#334155' : '#e2e8f0',
                    },
                  }}
                />
              </Box>
            </Box>
          </Box>

          {/* Footer with Save button */}
          <Box
            sx={{
              p: 2,
              borderTop: isDark ? '1px solid #334155' : '1px solid #e2e8f0',
            }}
          >
            <Button
              fullWidth
              variant="contained"
              onClick={handleSave}
              disabled={isSaving}
              startIcon={<Save />}
              sx={{
                background: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
                '&:hover': {
                  background: 'linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%)',
                },
                '&:disabled': {
                  background: isDark ? '#334155' : '#e2e8f0',
                  color: isDark ? '#64748b' : '#94a3b8',
                },
              }}
            >
              {isSaving ? 'Saving...' : 'Save'}
            </Button>
          </Box>
        </>
      )}
    </Box>
  );
}

