'use client';

import React, { useState, useEffect } from 'react';
import Box from '@mui/material/Box';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import IconButton from '@mui/material/IconButton';
import MenuItem from '@mui/material/MenuItem';
import { Close, Save, Add, Delete, ArrowBack } from '@mui/icons-material';
import { useDarkMode } from '../../../../hooks/useDarkMode';
import { useDialog } from '../../../../components/providers/DialogProvider';
import {
  getOperationDescription,
  upsertOperationDescription,
} from '../../../../../../lib/db/helper-path-operation-descriptions';
import { generateOperationId } from '../../../../../../lib/utils/path-utils';
import {
  getParametersForOperation,
  createPathParameter,
  deletePathParameter,
} from '../../../../../../lib/db/helper-path-parameters';
import { extractPathParameters } from '../../../../../../lib/utils/path-params';

interface OperationPropertiesPanelProps {
  operationId: string | null;
  operation: string;
  pathname: string;
  onClose: () => void;
  onRefresh?: () => void;
}

// View modes for the panel
type ViewMode = 'operation' | 'add-parameter';

export default function OperationPropertiesPanel({
  operationId,
  operation,
  pathname,
  onClose,
  onRefresh,
}: OperationPropertiesPanelProps) {
  const isDark = useDarkMode();
  const { alert: alertDialog, confirm: confirmDialog } = useDialog();

  // View mode state
  const [viewMode, setViewMode] = useState<ViewMode>('operation');

  // Operation state
  const [summary, setSummary] = useState('');
  const [description, setDescription] = useState('');
  const [operationIdName, setOperationIdName] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [saveStatus, setSaveStatus] = useState<'idle' | 'saved'>('idle');

  // Parameters list state
  const [parameters, setParameters] = useState<any[]>([]);
  const [parametersLoading, setParametersLoading] = useState(false);
  const [availablePathParams, setAvailablePathParams] = useState<string[]>([]);

  // New parameter form state
  const [newParamName, setNewParamName] = useState('');
  const [newParamLocation, setNewParamLocation] = useState<'path' | 'query' | 'header' | 'cookie'>('path');
  const [newParamSummary, setNewParamSummary] = useState('');
  const [newParamDescription, setNewParamDescription] = useState('');
  const [newParamRequired, setNewParamRequired] = useState(true);

  // Load operation description when operationId changes
  useEffect(() => {
    if (!operationId) {
      setSummary('');
      setDescription('');
      setOperationIdName('');
      return;
    }

    const loadDescription = async () => {
      setIsLoading(true);
      try {
        const result = await getOperationDescription(operationId);
        const desc = JSON.parse(result);

        if (desc) {
          setSummary(desc.summary || '');
          setDescription(desc.description || '');
          setOperationIdName(desc.operation_id || '');
        } else {
          const autoGenerated = generateOperationId(pathname, operation);
          setOperationIdName(autoGenerated);
        }
      } catch (error) {
        console.error('Error loading operation description:', error);
      } finally {
        setIsLoading(false);
      }
    };

    loadDescription();
  }, [operationId, pathname, operation]);

  // Load parameters when operationId changes
  useEffect(() => {
    if (!operationId) {
      setParameters([]);
      return;
    }

    const loadParameters = async () => {
      setParametersLoading(true);
      try {
        const result = await getParametersForOperation(operationId);
        const data = JSON.parse(result);
        if (data.success) {
          setParameters(data.parameters || []);
        }
      } catch (error) {
        console.error('Error loading parameters:', error);
      } finally {
        setParametersLoading(false);
      }
    };

    loadParameters();
  }, [operationId]);

  // Extract available path parameters from pathname
  useEffect(() => {
    if (pathname) {
      const params = extractPathParameters(pathname);
      setAvailablePathParams(params);
    }
  }, [pathname]);

  // Reset view mode when operationId changes
  useEffect(() => {
    setViewMode('operation');
    resetNewParamForm();
  }, [operationId]);

  const resetNewParamForm = () => {
    setNewParamName('');
    // Default to 'query' if no path parameters available, otherwise 'path'
    setNewParamLocation(availablePathParams.length > 0 ? 'path' : 'query');
    setNewParamSummary('');
    setNewParamDescription('');
    setNewParamRequired(availablePathParams.length > 0);
  };

  const handleSaveOperation = async () => {
    if (!operationId) return;

    setIsSaving(true);
    setSaveStatus('idle');
    try {
      await upsertOperationDescription(
        operationId,
        summary,
        description,
        operationIdName
      );
      // Show "Saved" in button briefly
      setSaveStatus('saved');
      setTimeout(() => setSaveStatus('idle'), 2000);
    } catch (error) {
      console.error('Error saving operation description:', error);
      await alertDialog({
        title: 'Error',
        message: 'Failed to save operation description. Please try again.',
        variant: 'error',
      });
    } finally {
      setIsSaving(false);
    }
  };

  const handleSaveParameter = async () => {
    if (!operationId || !newParamName.trim()) return;

    setIsSaving(true);
    try {
      const result = await createPathParameter(
        operationId,
        newParamName.trim(),
        newParamLocation,
        newParamSummary.trim() || undefined,
        newParamDescription.trim() || undefined,
        { required: newParamRequired }
      );
      const parsed = JSON.parse(result);

      if (parsed.success) {
        // Reload parameters list locally
        const paramsResult = await getParametersForOperation(operationId);
        const paramsData = JSON.parse(paramsResult);
        if (paramsData.success) {
          setParameters(paramsData.parameters || []);
        }

        // Switch back to operation view
        setViewMode('operation');
        resetNewParamForm();

        // Trigger canvas refresh if callback provided
        if (onRefresh) {
          onRefresh();
        }
      } else {
        await alertDialog({
          title: 'Error',
          message: parsed.error || 'Failed to add parameter',
          variant: 'error',
        });
      }
    } catch (error) {
      console.error('Error adding parameter:', error);
      await alertDialog({
        title: 'Error',
        message: 'Failed to add parameter. Please try again.',
        variant: 'error',
      });
    } finally {
      setIsSaving(false);
    }
  };

  const handleDeleteParameter = async (paramId: string, paramName: string) => {
    const confirmed = await confirmDialog({
      title: 'Delete Parameter',
      message: `Are you sure you want to delete the parameter "${paramName}"?`,
      variant: 'danger',
      confirmLabel: 'Delete',
      cancelLabel: 'Cancel',
    });

    if (!confirmed) return;

    try {
      const result = await deletePathParameter(paramId);
      const parsed = JSON.parse(result);

      if (parsed.success) {
        // Update local state
        setParameters(params => params.filter(p => p.id !== paramId));

        // Trigger canvas refresh if callback provided
        if (onRefresh) {
          onRefresh();
        }
      } else {
        await alertDialog({
          title: 'Error',
          message: parsed.error || 'Failed to delete parameter',
          variant: 'error',
        });
      }
    } catch (error) {
      console.error('Error deleting parameter:', error);
    }
  };

  const handleAddParameterClick = () => {
    resetNewParamForm();
    setViewMode('add-parameter');
  };

  const handleBackToOperation = () => {
    setViewMode('operation');
    resetNewParamForm();
  };

  if (!operationId) return null;

  return (
    <Box
      sx={{
        width: 320,
        height: '100%',
        borderLeft: isDark ? '1px solid #334155' : '1px solid #e2e8f0',
        background: isDark
          ? 'linear-gradient(180deg, #1e293b 0%, #0f172a 100%)'
          : 'linear-gradient(180deg, #ffffff 0%, #f8fafc 100%)',
        display: 'flex',
        flexDirection: 'column',
      }}
    >
      {/* Header */}
      <Box
        sx={{
          p: 2,
          borderBottom: isDark ? '1px solid #334155' : '1px solid #e2e8f0',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
        }}
      >
        {viewMode === 'add-parameter' ? (
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
            <IconButton size="small" onClick={handleBackToOperation} sx={{ color: isDark ? '#94a3b8' : '#64748b' }}>
              <ArrowBack sx={{ fontSize: 18 }} />
            </IconButton>
            <Box>
              <span className="text-sm font-semibold text-gray-900 dark:text-white">
                Add Parameter
              </span>
              <div className="text-xs text-gray-500 dark:text-gray-400 mt-0.5">
                {operation} {pathname}
              </div>
            </Box>
          </Box>
        ) : (
          <Box>
            <span className="text-sm font-semibold text-gray-900 dark:text-white">
              Operation Details
            </span>
            <div className="text-xs text-gray-500 dark:text-gray-400 mt-1">
              {operation} {pathname}
            </div>
          </Box>
        )}
        <IconButton size="small" onClick={onClose} sx={{ color: isDark ? '#94a3b8' : '#64748b' }}>
          <Close sx={{ fontSize: 18 }} />
        </IconButton>
      </Box>

      {/* Content */}
      {isLoading ? (
        <Box sx={{ p: 3, display: 'flex', justifyContent: 'center' }}>
          <span className="text-sm text-gray-500 dark:text-gray-400">Loading...</span>
        </Box>
      ) : viewMode === 'add-parameter' ? (
        /* Add Parameter Form */
        <>
          <Box sx={{ flex: 1, overflow: 'auto', p: 2 }}>
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
              {/* Parameter Name */}
              <Box>
                <label className="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Parameter Name <span className="text-red-500">*</span>
                </label>
                {newParamLocation === 'path' && availablePathParams.length > 0 ? (
                  <TextField
                    fullWidth
                    select
                    size="small"
                    value={newParamName}
                    onChange={(e) => setNewParamName(e.target.value)}
                    sx={{
                      '& .MuiInputBase-root': {
                        fontSize: '0.875rem',
                        backgroundColor: isDark ? '#0f172a' : '#ffffff',
                        color: isDark ? '#f1f5f9' : '#0f172a',
                      },
                      '& .MuiOutlinedInput-notchedOutline': {
                        borderColor: isDark ? '#334155' : '#e2e8f0',
                      },
                    }}
                  >
                    <MenuItem value="">Select a path parameter</MenuItem>
                    {availablePathParams.map((param) => (
                      <MenuItem key={param} value={param}>
                        {param}
                      </MenuItem>
                    ))}
                  </TextField>
                ) : (
                  <TextField
                    fullWidth
                    size="small"
                    value={newParamName}
                    onChange={(e) => setNewParamName(e.target.value)}
                    placeholder={
                      newParamLocation === 'query' ? 'e.g., limit, offset, filter' :
                      newParamLocation === 'header' ? 'e.g., Authorization, X-Request-ID' :
                      newParamLocation === 'cookie' ? 'e.g., session, token' :
                      'e.g., userId, groupId'
                    }
                    sx={{
                      '& .MuiInputBase-root': {
                        fontSize: '0.875rem',
                        backgroundColor: isDark ? '#0f172a' : '#ffffff',
                        color: isDark ? '#f1f5f9' : '#0f172a',
                      },
                      '& .MuiOutlinedInput-notchedOutline': {
                        borderColor: isDark ? '#334155' : '#e2e8f0',
                      },
                    }}
                  />
                )}
                {newParamLocation === 'path' && availablePathParams.length > 0 && (
                  <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                    Select from path parameters in: {pathname}
                  </p>
                )}
              </Box>

              {/* Location */}
              <Box>
                <label className="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Location <span className="text-red-500">*</span>
                </label>
                <div className="grid grid-cols-4 gap-1">
                  {(['path', 'query', 'header', 'cookie'] as const).map((loc) => {
                    const isPathDisabled = loc === 'path' && availablePathParams.length === 0;
                    return (
                      <button
                        key={loc}
                        type="button"
                        disabled={isPathDisabled}
                        onClick={() => {
                          if (!isPathDisabled) {
                            setNewParamLocation(loc);
                            setNewParamName('');
                            setNewParamRequired(loc === 'path');
                          }
                        }}
                        className={`px-2 py-1.5 rounded text-xs font-medium transition-colors ${
                          isPathDisabled
                            ? 'bg-gray-100 dark:bg-gray-800 text-gray-400 dark:text-gray-600 cursor-not-allowed opacity-50'
                            : newParamLocation === loc
                              ? 'bg-purple-500 text-white'
                              : 'bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700'
                        }`}
                        title={isPathDisabled ? 'No path parameters in this route' : undefined}
                      >
                        {loc}
                      </button>
                    );
                  })}
                </div>
                {availablePathParams.length === 0 && (
                  <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                    Path has no parameters (e.g., {'{'}userId{'}'})
                  </p>
                )}
              </Box>

              {/* Required */}
              <Box>
                <label className="flex items-center gap-2 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={newParamRequired}
                    onChange={(e) => setNewParamRequired(e.target.checked)}
                    className="w-4 h-4 rounded border-gray-300 text-purple-600 focus:ring-purple-500"
                  />
                  <span className="text-xs text-gray-700 dark:text-gray-300">
                    Required parameter
                  </span>
                </label>
              </Box>

              {/* Summary */}
              <Box>
                <label className="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Summary
                </label>
                <TextField
                  fullWidth
                  size="small"
                  value={newParamSummary}
                  onChange={(e) => setNewParamSummary(e.target.value)}
                  placeholder="Brief description"
                  sx={{
                    '& .MuiInputBase-root': {
                      fontSize: '0.875rem',
                      backgroundColor: isDark ? '#0f172a' : '#ffffff',
                      color: isDark ? '#f1f5f9' : '#0f172a',
                    },
                    '& .MuiOutlinedInput-notchedOutline': {
                      borderColor: isDark ? '#334155' : '#e2e8f0',
                    },
                  }}
                />
              </Box>

              {/* Description */}
              <Box>
                <label className="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Description
                </label>
                <TextField
                  fullWidth
                  multiline
                  rows={4}
                  size="small"
                  value={newParamDescription}
                  onChange={(e) => setNewParamDescription(e.target.value)}
                  placeholder="Detailed description..."
                  sx={{
                    '& .MuiInputBase-root': {
                      fontSize: '0.875rem',
                      backgroundColor: isDark ? '#0f172a' : '#ffffff',
                      color: isDark ? '#f1f5f9' : '#0f172a',
                    },
                    '& .MuiOutlinedInput-notchedOutline': {
                      borderColor: isDark ? '#334155' : '#e2e8f0',
                    },
                  }}
                />
              </Box>
            </Box>
          </Box>

          {/* Footer with Save button */}
          <Box
            sx={{
              p: 2,
              borderTop: isDark ? '1px solid #334155' : '1px solid #e2e8f0',
            }}
          >
            <Button
              fullWidth
              variant="contained"
              onClick={handleSaveParameter}
              disabled={isSaving || !newParamName.trim()}
              startIcon={<Save />}
              sx={{
                background: 'linear-gradient(135deg, #8b5cf6 0%, #a78bfa 100%)',
                '&:hover': {
                  background: 'linear-gradient(135deg, #7c3aed 0%, #8b5cf6 100%)',
                },
                '&:disabled': {
                  background: isDark ? '#334155' : '#e2e8f0',
                  color: isDark ? '#64748b' : '#94a3b8',
                },
              }}
            >
              {isSaving ? 'Saving...' : 'Save'}
            </Button>
          </Box>
        </>
      ) : (
        /* Operation Details Form */
        <>
          <Box sx={{ flex: 1, overflow: 'auto', p: 2 }}>
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
              {/* Operation ID */}
              <Box>
                <label className="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Operation ID
                </label>
                <TextField
                  fullWidth
                  size="small"
                  value={operationIdName}
                  onChange={(e) => setOperationIdName(e.target.value)}
                  placeholder="Auto-generated from path and verb"
                  sx={{
                    '& .MuiInputBase-root': {
                      fontSize: '0.875rem',
                      backgroundColor: isDark ? '#0f172a' : '#ffffff',
                      color: isDark ? '#f1f5f9' : '#0f172a',
                    },
                    '& .MuiOutlinedInput-notchedOutline': {
                      borderColor: isDark ? '#334155' : '#e2e8f0',
                    },
                  }}
                />
                <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                  Used for code generation and API client SDKs
                </p>
              </Box>

              {/* Summary */}
              <Box>
                <label className="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Summary
                </label>
                <TextField
                  fullWidth
                  size="small"
                  value={summary}
                  onChange={(e) => setSummary(e.target.value)}
                  placeholder="Brief summary of the operation"
                  sx={{
                    '& .MuiInputBase-root': {
                      fontSize: '0.875rem',
                      backgroundColor: isDark ? '#0f172a' : '#ffffff',
                      color: isDark ? '#f1f5f9' : '#0f172a',
                    },
                    '& .MuiOutlinedInput-notchedOutline': {
                      borderColor: isDark ? '#334155' : '#e2e8f0',
                    },
                  }}
                />
              </Box>

              {/* Description */}
              <Box>
                <label className="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Description
                </label>
                <TextField
                  fullWidth
                  multiline
                  rows={4}
                  size="small"
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  placeholder="Detailed description of what this operation does..."
                  sx={{
                    '& .MuiInputBase-root': {
                      fontSize: '0.875rem',
                      backgroundColor: isDark ? '#0f172a' : '#ffffff',
                      color: isDark ? '#f1f5f9' : '#0f172a',
                    },
                    '& .MuiOutlinedInput-notchedOutline': {
                      borderColor: isDark ? '#334155' : '#e2e8f0',
                    },
                  }}
                />
              </Box>

              {/* Parameters Section */}
              <Box sx={{ mt: 2 }}>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 1 }}>
                  <label className="block text-xs font-medium text-gray-700 dark:text-gray-300">
                    Parameters
                  </label>
                  <Button
                    size="small"
                    startIcon={<Add />}
                    onClick={handleAddParameterClick}
                    sx={{
                      fontSize: '0.75rem',
                      textTransform: 'none',
                      color: '#6366f1',
                      '&:hover': {
                        backgroundColor: isDark ? 'rgba(99, 102, 241, 0.1)' : 'rgba(99, 102, 241, 0.05)',
                      },
                    }}
                  >
                    Add Parameter
                  </Button>
                </Box>

                {parametersLoading ? (
                  <Box sx={{ py: 2, textAlign: 'center' }}>
                    <span className="text-xs text-gray-500 dark:text-gray-400">Loading parameters...</span>
                  </Box>
                ) : parameters.length === 0 ? (
                  <Box
                    sx={{
                      py: 3,
                      px: 2,
                      textAlign: 'center',
                      border: isDark ? '1px dashed #334155' : '1px dashed #e2e8f0',
                      borderRadius: 1,
                    }}
                  >
                    <span className="text-xs text-gray-500 dark:text-gray-400">
                      No parameters defined yet
                    </span>
                  </Box>
                ) : (
                  <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
                    {parameters.map((param) => (
                      <Box
                        key={param.id}
                        sx={{
                          p: 1.5,
                          border: isDark ? '1px solid #334155' : '1px solid #e2e8f0',
                          borderRadius: 1,
                          backgroundColor: isDark ? '#0f172a' : '#f9fafb',
                          display: 'flex',
                          justifyContent: 'space-between',
                          alignItems: 'start',
                        }}
                      >
                        <Box sx={{ flex: 1, minWidth: 0 }}>
                          <div className="text-xs font-medium text-gray-900 dark:text-white truncate">
                            {param.name}
                          </div>
                          <div className="text-[10px] text-gray-500 dark:text-gray-400 mt-0.5">
                            {param.in_location} • {param.metadata?.required ? 'required' : 'optional'}
                          </div>
                        </Box>
                        <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
                          <Box
                            sx={{
                              px: 1,
                              py: 0.5,
                              borderRadius: 0.5,
                              fontSize: '0.625rem',
                              fontWeight: 600,
                              color: '#fff',
                              backgroundColor:
                                param.in_location === 'path' ? '#8b5cf6' :
                                param.in_location === 'query' ? '#3b82f6' :
                                param.in_location === 'header' ? '#f59e0b' :
                                '#10b981',
                            }}
                          >
                            {param.in_location === 'path' ? '/' :
                             param.in_location === 'query' ? '?' :
                             param.in_location === 'header' ? 'H' : 'C'}
                          </Box>
                          <IconButton
                            size="small"
                            onClick={() => handleDeleteParameter(param.id, param.name)}
                            sx={{
                              color: '#ef4444',
                              p: 0.5,
                              '&:hover': { backgroundColor: 'rgba(239, 68, 68, 0.1)' },
                            }}
                          >
                            <Delete sx={{ fontSize: 14 }} />
                          </IconButton>
                        </Box>
                      </Box>
                    ))}
                  </Box>
                )}
              </Box>
            </Box>
          </Box>

          {/* Footer with Save button */}
          <Box
            sx={{
              p: 2,
              borderTop: isDark ? '1px solid #334155' : '1px solid #e2e8f0',
            }}
          >
            <Button
              fullWidth
              variant="contained"
              onClick={handleSaveOperation}
              disabled={isSaving}
              startIcon={<Save />}
              sx={{
                background: saveStatus === 'saved'
                  ? 'linear-gradient(135deg, #10b981 0%, #34d399 100%)'
                  : 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
                '&:hover': {
                  background: saveStatus === 'saved'
                    ? 'linear-gradient(135deg, #059669 0%, #10b981 100%)'
                    : 'linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%)',
                },
                '&:disabled': {
                  background: isDark ? '#334155' : '#e2e8f0',
                  color: isDark ? '#64748b' : '#94a3b8',
                },
              }}
            >
              {isSaving ? 'Saving...' : saveStatus === 'saved' ? 'Saved ✓' : 'Save'}
            </Button>
          </Box>
        </>
      )}
    </Box>
  );
}

