name: objectified-cli

on:
  push:
    paths:
      - "objectified-cli/**"
      - ".github/workflows/objectified-cli.yml"
      - "yarn.lock"
      - "package.json"
  pull_request:
    paths:
      - "objectified-cli/**"
      - ".github/workflows/objectified-cli.yml"
      - "yarn.lock"
      - "package.json"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo "Do nothing"

