name: objectified-openapi

on:
  push:
    paths:
      - "objectified-rest/openapi.*"
  pull_request:
    paths:
      - "objectified-rest/openapi.*"

jobs:
  publish:
    runs-on: self-hosted
    env:
      OBJECTIFIED_API_KEY: ${{ secrets.OBJECTIFIED_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Build CLI and push OpenAPI to catalog
        run: |
          cd objectified-cli
          uv sync
          ./run.sh --tenant=objectified import openapi ../objectified-rest/openapi.yaml --publish public --poll-interval 1000
        env:
          OBJECTIFIED_LOAD_DOTENV: "0"
